fix #2925- Loader animation added
openMF/community-app pull request #2947
Opened 2018-05-06 15:28 UTC by anweshknayak

## Description
New loader animation. Please refer issue for more details

also changes due to #2946 there are some minor changes in some lines for
`styles.css` which resulted in a large diff.

## Related issues and discussion
#2925 
## Screenshots, if any

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Validate the JS and HTML files with `grunt validate` to detect errors and potential problems in JavaScript code.

- [ ] Run the tests by opening `test/SpecRunner.html` in the browser to make sure you didn't break anything.

- [ ] If you have multiple commits please combine them into one commit by squashing them.

- [ ] Read and understood the contribution guidelines at `community-app/Contributing.md`.

2018-05-16 08:32 UTC, botraunak requested changes
Why do we need to update the gruntfile for changing the loader animation?

2018-05-16 08:43 UTC, botraunak commented
@anweshknayak  I have merged the grunt file changes please rebase and submit new PR without the gruntfile changes.

2018-05-16 09:10 UTC, anweshknayak commented
@botraunak I think you can directly have `rebase and merge` option in the github itself. Can you do it?

2018-05-16 09:16 UTC, anweshknayak commented
@botraunak done.
Grunt file changes to include `compass:dev` for everytime we make changes in scss file. It will automatically convert to css.

2018-05-16 09:36 UTC, botraunak commented
@anweshknayak The diff is not visible when performing the rebase and merge, Can you do this and update the PR, and all the other PRs which rely on it. It's necessary to have only the diff the relates to the issue and not related issues.

2018-05-16 09:42 UTC, anweshknayak commented
@botraunak diff it is due to the changes done in Grunt file configurations related to `compass:dev` . I. t lints the css file and add comments from which scss file it was added. Diff is not visible because the change is large. Click it the changes will appear.

And this is not due to any other PRs

2018-05-16 09:49 UTC, anweshknayak commented
Also if diff is not appearing. Could you pull this PR locally and check ?

2018-05-16 09:51 UTC, botraunak approved these changes
Looks okay to me

2018-05-16 09:54 UTC, botraunak requested changes

2018-05-16 09:54 UTC, botraunak commented on Gruntfile.js
> +  grunt.registerTask('serve', ['clean:server', 'copy:server', 'compass:dev', 'connect:livereload', 'watch']);
Isn't this already included in the watch task check under css, of the watch task definition!

2018-05-16 09:55 UTC, botraunak commented on Gruntfile.js
> +  grunt.registerTask('serve', ['clean:server', 'copy:server', 'compass:dev', 'connect:livereload', 'watch']);
Now that you have fixed the compass:dev I don't think you need to call this in the serve task explicitly as it's already being done in the watch task :)

2018-05-16 10:03 UTC, anweshknayak commented
@botraunak done

2018-05-17 06:08 UTC, anweshknayak commented
@botraunak I tried removing `compass:dev` from grunt serve task. The difference is we have to keep running grunt serve for changes to incorporate.

If we already include `compass:dev` and make changes and scss and start `grunt serve` changes are being incorporated in scss otherwise it is not. Hope it makes sense

2018-05-17 06:35 UTC, botraunak approved these changes

2018-05-17 06:38 UTC, merged