Fixes issue #3001. datepicker disables dates before 1st Jan
openMF/community-app pull request #3008
Opened 2018-09-01 19:41 UTC by terencemo

## Description
Describe the changes made and why they were made instead of how they were made.

## Related issues and discussion
#{Issue Number}

## Screenshots, if any

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Validate the JS and HTML files with `grunt validate` to detect errors and potential problems in JavaScript code.

- [ ] Run the tests by opening `test/SpecRunner.html` in the browser to make sure you didn't break anything.

- [ ] If you have multiple commits please combine them into one commit by squashing them.

- [ ] Read and understood the contribution guidelines at `community-app/Contributing.md`.

2018-09-04 09:58 UTC, ShruthiRajaram requested changes
Make similar changes for DateTime field also

2018-09-04 14:09 UTC, terencemo commented
Suggest that we track that as a separate issue.

2018-09-05 06:06 UTC, ShruthiRajaram commented
@terencemo thanks for sharing guidelines.  Yes, the date  time issue is easily identifiable and should have been covered in the issue.
I suggested additional fix with existing change, since both will affect date field and if user wants to have a date time field instead of date field, the PR will not serve solution completely. At that time you will end up creating one more issue and a separate PR for the same date field. Technically this should have been covered in the issue, but wasn't. 
Its up-to you how you want to proceed.

2018-09-05 07:56 UTC, terencemo commented
@ShruthiRajaram currently I don't have bandwidth to test the DateTime field and I think it should be a separate issue. If you disagree, let me know and I'll close the PR or you can do so yourself.

2020-08-06 23:47 UTC, edcable commented
@terencemo Are you able to create a separate ticket for DateTime field and then we can merge and close this.

2020-08-06 23:49 UTC, edcable commented
Never mind I see that you already did that at #3092

2020-08-06 23:49 UTC, merged