Country was not showing in Client's address page in issue
openMF/community-app pull request #3044
Opened 2018-11-09 07:30 UTC by elirehema

## Description
Resolved the countries selection problem by pointing out the list from empty list stateOptions to countryOptions

## Related issues and discussion
#3019

## Screenshots, if any

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Validate the JS and HTML files with `grunt validate` to detect errors and potential problems in JavaScript code.

- [ ] Run the tests by opening `test/SpecRunner.html` in the browser to make sure you didn't break anything.

- [ ] If you have multiple commits please combine them into one commit by squashing them.

- [ ] Read and understood the contribution guidelines at `community-app/Contributing.md`.

2018-11-09 12:29 UTC, ShruthiRajaram requested changes
Changing state to country is not the right way.  If I am not wrong change the ng-show="country" to ng-show="countryId" in addressForm html page. You will be able to fix the issue.

2018-11-09 12:45 UTC, elirehema commented
@ShruthiRajaram any reason in short if possible,  while working on your request.

2018-11-09 12:48 UTC, ShruthiRajaram commented
@elirehema kindly check the previous comment. You will be able to solve the issue with that.

2018-11-09 12:56 UTC, elirehema commented
Okay @ShruthiRajaram am working on it as soon as possible.

2018-11-22 01:44 UTC, bauripalash commented
@elirehema Any Update?

2018-11-28 09:35 UTC, elirehema commented
@ShruthiRajaram @bauripalash  I have resolved it and and updated the commit

2018-11-28 12:04 UTC, bauripalash requested changes
Can you please add screenshots?

2018-12-03 08:10 UTC, elirehema commented
@bauripalash check out on my PR, you can see the changes.

2018-12-03 08:49 UTC, ShruthiRajaram requested changes

2018-12-03 08:49 UTC, ShruthiRajaram commented on app/views/administration/AddressForm.html
> +                            ng-options="countryOption.id as countryOption.name for countryOption in countryOptions track by countryOption.id"
these changes are not correct. Do not change the state field to country.

2018-12-03 08:49 UTC, ShruthiRajaram commented on app/views/administration/AddressForm.html
> +            <div class="form-group" ng-show="countryId">
Only this change is required

2018-12-14 07:09 UTC, ShruthiRajaram approved these changes

2018-12-14 07:09 UTC, merged