Feat #2935 - Add UI for editing submitted on date for groups
openMF/community-app pull request #3059
Opened 2018-12-11 21:56 UTC by m-sameer

## Description
Add UI for editing **submitted on** date for groups.

## Related issues and discussion
#2935

## Screenshots, if any
![screenshot from 2018-12-12 03-17-26](https://user-images.githubusercontent.com/28915865/49832677-5aded780-fdbd-11e8-8d13-8aee8543d5d3.png)

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Validate the JS and HTML files with `grunt validate` to detect errors and potential problems in JavaScript code.

- [x] Run the tests by opening `test/SpecRunner.html` in the browser to make sure you didn't break anything.

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `community-app/Contributing.md`.

2018-12-12 07:55 UTC, ShruthiRajaram requested changes

2018-12-12 07:55 UTC, ShruthiRajaram commented on app/scripts/controllers/groups/EditGroupController.js
> +                if (data.timeline.submittedOnDate) {
data.timeline is not defined in this particular response. So the data.timeline will be undefined.

2018-12-12 07:55 UTC, ShruthiRajaram commented on app/scripts/controllers/groups/EditGroupController.js
> +                    const submitDate = dateFilter(data.timeline.submittedOnDate, scope.df);
instead you can write the code inside 'resourceFactory.groupResource.get  call'  or you can use the existing variable.

2018-12-12 16:09 UTC, m-sameer commented
@ShruthiRajaram I have updated the PR. Please review. :smile:

2018-12-13 05:44 UTC, ShruthiRajaram approved these changes

2018-12-13 05:44 UTC, merged