numericValidation-fxdDepProd
openMF/community-app pull request #3071
Opened 2018-12-24 10:35 UTC by Jov03

## Description
Used the numeric validation directive to validate fields in fixed New Deposit product view

## Related issues and discussion
#2809 

- [x] Validate the JS and HTML files with `grunt validate` to detect errors and potential problems in JavaScript code.

- [x] Run the tests by opening `test/SpecRunner.html` in the browser to make sure you didn't break anything.

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `community-app/Contributing.md`.

2018-12-24 13:43 UTC, abhaychawla reviewed
@Jov03 Looks good. Please update your commit message as per the guidelines to `Fix #issueno - Issue Description` and also mention the related issue id in your PR description so I can approve.

2018-12-24 14:20 UTC, Jov03 commented
@abhaychawla I updated the PR.

2018-12-24 14:25 UTC, abhaychawla approved these changes
Thanks!

2018-12-24 14:25 UTC, abhaychawla commented
@ShruthiRajaram please merge this PR.

2018-12-25 13:27 UTC, ShruthiRajaram requested changes

2018-12-25 13:27 UTC, ShruthiRajaram commented on app/views/products/createfixeddepositproduct.html
> +                                number-format ng-model="formData.depositAmount" required
deposit amount should include decimal values also . Issue reference -2985

2018-12-25 13:27 UTC, ShruthiRajaram commented on app/views/products/createfixeddepositproduct.html
> +                                number-format ng-model="formData.minDepositAmount" late-validate number=true />
same as deposit amount

2018-12-25 13:27 UTC, ShruthiRajaram commented on app/views/products/createfixeddepositproduct.html
> +                            <form-validate valattributeform="Terms" valattribute="maxDepositAmount" />
same as above

2018-12-25 15:28 UTC, Jov03 commented on app/views/products/createfixeddepositproduct.html
> +                                number-format ng-model="formData.depositAmount" required
@ShruthiRajaram  ok ill make the necessary changes.

2018-12-28 08:49 UTC, Jov03 commented
@abhaychawla @ShruthiRajaram  I looked into issue 2985 as requested the decimal directive used there was updating the user input automatically not validating the textfield so i added decimal number attribute to existing late-validate directive to validate the textfields. I have attached a screenshot in PR description please have a look.

On a side note Travis Build is failing on inspecting the logs generated by travis it is due to connect.js file to which i have not made any changes but let me know if it is due to my changes to the code.

2018-12-29 18:35 UTC, abhaychawla commented
This is not being caused by your changes. It seems the Travis build is failing as the version of node js being used for the build doesn't support the ES6 syntax. If possible, please create an issue for the same and send a PR to update the version?

@ShruthiRajaram, as @Jov03 said above a validation message is not being shown where decimals directive is being used rather the field gets updated automatically, is it deliberate or a different approach should be followed as in the updated PR?

2018-12-31 06:46 UTC, ShruthiRajaram approved these changes

2018-12-31 06:49 UTC, ShruthiRajaram commented
@Jov03 raise the PR again and try to get a successful Travis build. once Travis build is success will merge the PR.

2018-12-31 11:53 UTC, Jov03 commented
@ShruthiRajaram i raised the PR again and build failed due to same reason as explained in issue #3077. Please have a look.

2019-01-09 12:06 UTC, Jov03 commented
Will close this PR and re-open it to see if it makes any difference.

2019-03-02 17:04 UTC, Jov03 commented
@ShruthiRajaram @abhaychawla after recent PR#3087 merge my PR passed  Travis build please have a look.

2019-03-05 05:27 UTC, merged