Dockerize Community App
openMF/community-app pull request #3107
Opened 2019-06-21 17:16 UTC by awasum

Dockerize Community App.
Update readme with intructions on how to build.
Docker image is created and app is run in nginx when image is executed.

Fix #3106

2019-07-01 22:33 UTC, awasum commented
I wonder why this is failing. Does anyone know why?

2019-07-11 07:10 UTC, vorburger reviewed
> I wonder why this is failing. Does anyone know why?

Isn't [the Travis build failure](https://travis-ci.com/openMF/community-app/builds/117581158) completely unrelated to this PR? This PR just adds a Dockerfile. That failure is Travis broken - without Docker, just "plain" Travis (which does something similar to what you're adding here - BTW perhaps it would be possible to share the steps?). I just raised #3110, and expect it to fail similarly.

2019-07-11 07:10 UTC, vorburger commented on README.md
> +Access the webapp on http://localhost in your browser. Ma
```suggestion
Access the webapp on http://localhost in your browser.
```

2019-07-11 07:10 UTC, vorburger commented on README.md
> +port 80 within the container
```suggestion
on port 80 within the container.
```

2019-07-11 07:14 UTC, vorburger commented
@awasum may I make a suggestion? I noticed how the steps you're adding into the Dockerfile and what the README describes for manual steps and [what's in the .travis.yml](https://github.com/openMF/community-app/blob/develop/.travis.yml) are, naturally, very similar... how about extracting that from `.travis.yml` out into a (new) `build.sh` and making `.travis.yml` just call that `build.sh` (in a new PR, separate from this one; once the basic Travis build itself is fixed again), and then in your `Dockerfile` introduced in this PR just `COPY` and `RUN` that `build.sh` - do you know what I mean? I feel that could reduce future double maintenance hassles.

2019-07-16 09:02 UTC, awasum commented on README.md
> +Access the webapp on http://localhost in your browser. Ma
Thanks

2019-07-16 09:02 UTC, awasum commented on README.md
> +port 80 within the container
Thanks

2019-07-16 09:03 UTC, awasum commented
> @awasum may I make a suggestion? I noticed how the steps you're adding into the Dockerfile and what the README describes for manual steps and [what's in the .travis.yml](https://github.com/openMF/community-app/blob/develop/.travis.yml) are, naturally, very similar... how about extracting that from `.travis.yml` out into a (new) `build.sh` and making `.travis.yml` just call that `build.sh` (in a new PR, separate from this one; once the basic Travis build itself is fixed again), and then in your `Dockerfile` introduced in this PR just `COPY` and `RUN` that `build.sh` - do you know what I mean? I feel that could reduce future double maintenance hassles.

Yeah, I think I understand you. create the build.sh with similar steps and call the file in travis.yml and in docker for consistency.

2019-07-23 08:24 UTC, vorburger commented
@awasum I don't mean to "pile on" more (it's super cool that you are working on this!), but in an ideal world, I'd love the Dockerfile here to be "multi stage" (see https://docs.docker.com/develop/develop-images/multistage-build/ ...) as well, just like just proposed over in https://github.com/apache/fineract/pull/624 for the back-end, and so cleanly separate the builder image running all the fancy JS Node/whatever build related stuff and the runtime image which "just" serves the (static) result.

2019-07-23 08:27 UTC, vorburger requested changes
@awasum did you mean to apply suggested (minor..) improvements, or were you hoping thisfor this to get merged as is already?

2019-07-23 08:29 UTC, awasum commented
> @awasum did you mean to apply suggested (minor..) improvements, or were you hoping thisfor this to get merged as is already?

Will add your improvements before merging....

2019-07-23 08:32 UTC, awasum commented
> @awasum I don't mean to "pile on" more (it's super cool that you are working on this!), but in an ideal world, I'd love the Dockerfile here to be "multi stage" (see https://docs.docker.com/develop/develop-images/multistage-build/ ...) as well, just like just proposed over in [apache/fineract#624](https://github.com/apache/fineract/pull/624) for the back-end, and so cleanly separate the builder image running all the fancy JS Node/whatever build related stuff and the runtime image which "just" serves the (static) result.

I am not sure I understand completely. I am using multi stage docker builds. Maybe am wrong cus I have ruby/node as builder to build the product package and then am copying from builder in nginx. Is there a better way? Please advice.. I hope to get this done this night. My time is GMT + 1.

2019-07-23 09:20 UTC, awasum commented
> It's cool to see that the Dockerfile here is "multi stage", just like just proposed over in [apache/fineract#624](https://github.com/apache/fineract/pull/624) for the back-end, and cleanly separates the builder image running all the fancy JS Node/whatever build related stuff and the runtime image which "just" serves the (static) result.
> 
> PS: Duh, I hadn't seen this before; thus preivous (now deleted) comment.

Yes...I realised this. Thanks.

2019-07-24 16:25 UTC, awasum commented
@vorburger ..I will delay with this till weekend..I have some work which just showed up at day job...Please..

Or if you have the time..go ahead and fix this and merge...

2019-08-05 15:04 UTC, belfazt commented
Hi, is this going to be updated? I'd like to take care of the changes if it's not

2019-08-05 15:05 UTC, awasum commented
Go ahead. @belfazt

2019-08-05 15:15 UTC, belfazt commented
Corrections can be found here https://github.com/openMF/community-app/pull/3117

2019-08-05 15:16 UTC, awasum commented
Do you want to also address this in this in that PR? https://github.com/openMF/community-app/pull/3107#issuecomment-510361027

2019-08-05 15:18 UTC, belfazt commented
I'd prefer to do that in a separate PR and then just apply that change to the `Dockerfile`, which I might do later

2019-08-05 15:19 UTC, awasum commented
Ok...Let Travis build.

2019-08-23 17:44 UTC, vorburger commented
This was merged in #3117 as dffcb3f1307a8311d17be8ae297c7ce70d3ad009.

I'd love to see a follow-up PR from @belfazt or @awasum re. unifying things; keeping #3106 open for that.

2019-08-23 17:44 UTC, closed without merging