FINERACT-802-restrict-client-to-have-single-self-service-user
openMF/community-app pull request #3152
Opened 2019-12-04 12:57 UTC by aimanoj

## Description
Error message added for the above fineract issue

## Related issues and discussion
#{Issue Number}

## Screenshots, if any

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Validate the JS and HTML files with `grunt validate` to detect errors and potential problems in JavaScript code.

- [ ] Run the tests by opening `test/SpecRunner.html` in the browser to make sure you didn't break anything.

- [ ] If you have multiple commits please combine them into one commit by squashing them.

- [ ] Read and understood the contribution guidelines at `community-app/Contributing.md`.

2020-08-06 23:52 UTC, edcable commented
@fynmanoj Can you address the merge conflict so we can merge this for upcoming release?

2020-08-07 07:35 UTC, fynmanoj commented
merge conflict resolved 
@edcable

2020-08-14 18:12 UTC, luckyman20 requested changes
@fynmanoj There's still a merge conflict. Can you please resolve it so we can merge your Pull Request?

2020-08-14 18:12 UTC, luckyman20 commented on app/global-translations/locale-en.json
> +  "error.msg.user.self.service.user.already.exist" : "Self Service User Id is already created. Go to Admin->Users to edit or delete the self-service user.",
```suggestion
  "error.msg.user.self.service.user.already.exist" : "Self Service User ID is already created. Go to Admin -> Users to edit or delete the self-service user.",
```

2020-08-14 20:25 UTC, fynmanoj commented on app/global-translations/locale-en.json
> +  "error.msg.user.self.service.user.already.exist" : "Self Service User Id is already created. Go to Admin->Users to edit or delete the self-service user.",
done!

2020-08-17 12:51 UTC, luckyman20 approved these changes
Looks good, thanks @aimanoj!

2020-08-17 12:52 UTC, luckyman20 commented
@aimanoj @fynmanoj It still has a conflict. Can you please quickly fix it so that we can merge this?

2020-08-17 13:23 UTC, fynmanoj commented
> @aimanoj @fynmanoj It still has a conflict. Can you please quickly fix it so that we can merge this?

done!

2020-08-17 13:55 UTC, merged

2020-08-17 13:56 UTC, luckyman20 commented
@fynmanoj Thanks for the contribution!