Fix #2729 - Fixes edit button not aligned properly
openMF/community-app pull request #3170
Opened 2019-12-22 14:42 UTC by OussEmaDevCode

## Description
Aligned the button properly in the title of the loan products page.

## Related issues and discussion
#2729 

## Screenshots, if any
Before: 
![Capture d’écran (207)](https://user-images.githubusercontent.com/38397893/71323280-a9937700-24d1-11ea-9d10-c01868ef271b.png)

After:
![Capture d’écran (206)](https://user-images.githubusercontent.com/38397893/71323275-a26c6900-24d1-11ea-9086-1331bc091b2c.png)
## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Validate the JS and HTML files with `grunt validate` to detect errors and potential problems in JavaScript code.

- [x] Run the tests by opening `test/SpecRunner.html` in the browser to make sure you didn't break anything.

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `community-app/Contributing.md`.

2019-12-22 19:27 UTC, muskankhedia commented
@OussEmaDevCode Please refer to the comments in the [#2730](https://github.com/openMF/community-app/pull/2730). Please make the CSS changes in the sass file and then compile it using the sass command. You can follow the guide [https://sass-lang.com/guide](https://sass-lang.com/guide).

2019-12-22 21:29 UTC, abhaychawla commented
@muskankhedia He has used an already existing class.

2019-12-22 21:31 UTC, abhaychawla requested changes
@OussEmaDevCode The alignment should be inline with the heading. Something like in this screenshot: https://user-images.githubusercontent.com/8139783/34606432-580cbe4e-f235-11e7-93a4-dce87d77baf6.png Try again. Right now its in between the row of the heading and the content.

2019-12-22 22:19 UTC, OussEmaDevCode commented
@abhaychawla Done !! I have also updated the PR message with the new UI

2019-12-23 09:32 UTC, abhaychawla approved these changes
Good work!!

2019-12-23 13:48 UTC, muskankhedia commented
> @muskankhedia He has used an already existing class.

@abhaychawla I understand your point. Thank you.

2020-01-06 20:53 UTC, abhaychawla commented
@luckyman20 Please merge this.

2020-01-07 11:40 UTC, merged