Updated bower Dependencies
openMF/community-app pull request #3234
Opened 2020-05-17 19:02 UTC by muskankhedia

## Description
All the compatible libraries in the bower.json have been updated. The list of the updated libraries with their versions are as follows:

| Package Name        | Previous Version           | Updated Version  |
| ------------- |:-------------:| -----:|
| requirejs     | 2.2.0 | ^2.3.6 |
| require-css      | 0.1.8      |   ^0.1.10 |
| angular-translate | 2.7.2  |  2.18.2   |
| angular-translate-loader-static-files | 2.7.2      |   2.18.2 |
| ckeditor | 4.5.7   |   ^4.14.0 |
| angular-dynamic-locale |    | ^0.1.37 |
| bootstrap | ~3.3.3 | ^4.5.0 |
| bootstrap-sass | ~3.3.3  |    ^3.4.1 |
| angular-chosen-localytics |  ^1.4.0     | ^1.9.3    |
| almond | ^0.3.2    |  ^0.3.3  |
| angular-translate | ~2.11.0  | ^2.18.2 |

## Related issues and discussion
#3209 

## Screenshots, if any

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Validate the JS and HTML files with `grunt validate` to detect errors and potential problems in JavaScript code.

- [x] Run the tests by opening `test/SpecRunner.html` in the browser to make sure you didn't break anything.

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `community-app/Contributing.md`.

2020-05-17 21:08 UTC, abhaychawla commented
@muskankhedia Are we able to update angular version to 1.7 as well?

2020-05-18 03:19 UTC, muskankhedia commented
@abhaychawla One of the packages `angular-sanitize` is broken in the future release and there is an error as well `angular.lowercase is not a function` when we update it to `angular 1.7.9`. The description of the error has been explained in the [link](https://github.com/angular/angular.js/issues/16563). Also, all the angular packages should be in the same version for the best performance and utilisation. So I didn't upgrade the modules that would anyway break the application and also didn't update any of the angular packages.

2020-05-18 08:56 UTC, abhaychawla commented
@muskankhedia Are we able to use any of the workarounds mentioned at https://github.com/textAngular/textAngular/issues/1608 to tackle this?

2020-05-18 13:21 UTC, muskankhedia commented
@abhaychawla Thanks for the link, I found a solution to tackle the same. Now, it's working fine after upgrading the angular modules as well but needs changes in some files based on upgraded functionality. Will make the changes and upgrade the PR soon.

2020-05-19 12:54 UTC, abhaychawla commented
@muskankhedia They are minor changes?

2020-05-19 13:20 UTC, muskankhedia commented
@abhaychawla Yes somehow, needs changes in some files based on the updated modules.

2020-05-24 10:45 UTC, abhaychawla commented
@muskankhedia How soon can we make those changes? Can we target it by tomorrow?

2020-05-24 12:43 UTC, muskankhedia commented
Yaa sure. I will try to complete it by tomorrow.

2020-05-25 06:12 UTC, muskankhedia commented
@abhaychawla I tried fixing up the changes as mentioned in the [docs](https://code.angularjs.org/1.7.0-rc.0/docs/guide/migration#migrating-from-1-6-to-1-7) but still facing some errors with the Authenrication and the Notification modules. Can you please have a look at the same?

2020-05-25 19:22 UTC, abhaychawla commented
@muskankhedia Please share the screenshot of the error once again.

2020-05-26 14:53 UTC, muskankhedia commented
![Screenshot from 2020-05-26 20-21-15](https://user-images.githubusercontent.com/36980003/82915680-ade72300-9f8e-11ea-87d1-71b603b2cfcc.png)

This is the screenshot of the homepage with the console after making the changes.

2020-06-14 00:58 UTC, edcable commented
@abhaychawla and @muskankhedia have we made any progress on the errors that you were looking into?

2020-06-15 17:14 UTC, abhaychawla commented
@edcable Still need to look into it, I have been a bit preoccupied with office work. I will try to look at by next week.

2020-08-23 12:02 UTC, Jov03 requested changes
@muskankhedia you need to refer https://docs.angularjs.org/guide/migration . To make sure you have made the changes required to go from angular v1.5 to angular v1.6 then angular v1.6 to angular v1.7 

Right now the entire community app is not working in your PR due to 2 reasons:

1. incorrect handling of `$http.then`  method 
2. In angular v1.6  the default hash-prefix in url has been changed to (!)  so you need to add 
`$locationProvider.hashPrefix('');` in routes.js to set it back to empty string.
Refer : https://docs.angularjs.org/guide/migration#commit-aa077e8

@edcable is it necessary to update other dependencies too besides angular? If it is @muskankhedia you would need  to refer the changelog of each and every dependency version you are upgrading and make the necessary changes in code where that dependecy is used.

2020-08-23 12:02 UTC, Jov03 commented on app/scripts/controllers/main/MainController.js
> +            $http.get('release.json').then(function(data) {
```suggestion
            $http.get('release.json').then(function(response) {
            var data = response.data;
```

Refer : https://docs.angularjs.org/guide/migration#-http-

Note: The method signatures and return values are different. In Angular v1.5 success method used to return the following data:
`$http(...).
success(function onSuccess(data, status, headers, config) {
  // Handle success
  ...
}).
error(function onError(data, status, headers, config) {
  // Handle error
  ...
});`

but now it returns a single object containing the above mentioned property :

```
$http(...).
  then(function onSuccess(response) {
    // Handle success
    var data = response.data;
    var status = response.status;
    var statusText = response.statusText;
    var headers = response.headers;
    var config = response.config;
    ...
  }).
  catch(function onError(response) {
    // Handle error
    var data = response.data;
    var status = response.status;
    var statusText = response.statusText;
    var headers = response.headers;
    var config = response.config;
    ...
  });
```

2020-08-23 12:02 UTC, Jov03 commented on app/scripts/controllers/main/MainController.js
> +                $http.get('scripts/config/LogoConfig.json').then(function onSuccess(datas) {
Refer : https://docs.angularjs.org/guide/migration#-http-

2020-08-23 12:02 UTC, Jov03 commented on app/scripts/controllers/reports/XBRLController.js
> +                    .then(function (data) {
Refer : https://docs.angularjs.org/guide/migration#-http-

2020-08-23 12:02 UTC, Jov03 commented on app/scripts/controllers/reports/XBRLController.js
> +                }).then(function (data) {
Refer : https://docs.angularjs.org/guide/migration#-http-

2020-08-23 12:02 UTC, Jov03 commented on app/scripts/models/LoggedInUser.js
> +                if (role) {
Revert this if block. `data.roles` and 'data.selectedRoles' were undefined due to mistakes in `$http.then` method.

2020-08-23 12:02 UTC, Jov03 commented on app/scripts/modules/notificationWidget.js
> +                            if (jsonErrors) {
revert this if block and check the handling in `$http.then` method

2020-08-23 12:02 UTC, Jov03 commented on app/scripts/modules/notificationWidget.js
> +                                if(jsonErrors) {
revert this if block and check the handling in $http.then method

2020-08-23 12:02 UTC, Jov03 commented on app/scripts/services/UIConfigService.js
> +                .then(function(data) {
Refer : https://docs.angularjs.org/guide/migration#-http-

2020-08-24 20:14 UTC, edcable commented
@Jov03 for security reasons, we were trying to ensure that the dependencies were updates. @spider0061 are you able to assist at all here? Is this at all related to #3247

2020-08-24 20:28 UTC, muskankhedia commented
@edcable I am working to make the updates as reviewed by @Jov03 . I was working on some web-app issues and gsoc final documentation so couldn't get time much time for this PR. I will try to update it in a day or two.

2020-08-25 05:15 UTC, spider0061 commented
> @Jov03 for security reasons, we were trying to ensure that the dependencies were updates. @spider0061 are you able to assist at all here? Is this at all related to #3247

The issue with #3247 because of phantomjs. I am looking into it.

2020-08-30 12:58 UTC, Jov03 approved these changes
Thanks @muskankhedia !! This PR looks good.

2020-08-30 12:59 UTC, merged