Fixed missing address street field
openMF/community-app pull request #3344
Opened 2021-01-27 20:14 UTC by BLasan

## Description
See #3343 

## Related issues and discussion
#3343 

## Screenshots, if any
![Screenshot from 2021-01-28 01-43-15](https://user-images.githubusercontent.com/43112139/106047998-50e9d100-610a-11eb-9511-637a1fe2d0b0.png)

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Validate the JS and HTML files with `grunt validate` to detect errors and potential problems in JavaScript code.

- [ ] Run the tests by opening `test/SpecRunner.html` in the browser to make sure you didn't break anything.

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `community-app/Contributing.md`.

2021-01-27 20:14 UTC, BLasan commented
@bharathcgowda @spider0061  Please review

2021-01-29 12:00 UTC, bharathcgowda commented
@spider0061  Hi Ashutosh, would you please help us in reviewing and merging this?

2021-02-05 17:36 UTC, spider0061 commented
> @spider0061 Hi Ashutosh, would you please help us in reviewing and merging this?

Sure Sir.

2021-02-06 03:58 UTC, spider0061 approved these changes
LGTM!

2021-02-06 11:51 UTC, bharathcgowda commented
@edcable  can we get this merged by someone, or could I merge it as it is already being approved by @spider0061

2021-02-06 15:40 UTC, wkk91193 commented on app/scripts/controllers/client/CreateClientController.js
@BLasan Please remove the console log statements

2021-02-06 15:41 UTC, wkk91193 requested changes
@BLasan Please remove the console log statements

2021-02-06 15:46 UTC, BLasan commented
> @BLasan Please remove the console log statements

Done. Please review

2021-02-14 08:51 UTC, merged